name: festim-workshopx
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics-dolfinx
  - matplotlib
  - pip>=20.1
  - pyvista
  - ipywidgets
  - pip:
    - git+https://github.com/festim-dev/festim@fenicsx
    - pyparsing
    - ipykernel
    - nbconvert